# Generated by Django 4.2.6 on 2024-10-25 05:43

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.CharField(
                error_messages={
                    "error": "Пользователь с таким адресом электронной почты уже существует."
                },
                max_length=256,
                unique=True,
                verbose_name="адрес электронной почты",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                error_messages={"error": "Пользователь с таким именем уже существует"},
                help_text="не более 35 символов. Только буквы, цифры и @/./+/-/_.",
                max_length=35,
                unique=True,
                validators=[django.contrib.auth.validators.ASCIIUsernameValidator()],
                verbose_name="Логин",
            ),
        ),
    ]
